apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: fcm-dev
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          # bind to the pod IP, otherwise it's only localhost
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
    processors: {}
      # batch:
      # memory_limiter:
        # # 80% of maximum memory up to 2G
        # limit_mib: 200
        # 25% of limit up to 2G
        # spike_limit_mib: 64
        # check_interval: 5s
    # extensions:
    #  zpages: {}
    exporters:
      debug:
        verbosity: detailed
    service:
      # idk what this does?
      # extensions: [zpages]
      pipelines:
        logs:
          receivers: [otlp]
          # processors: [memory_limiter, batch]
          processors:
          exporters: [debug]
        traces:
          receivers: [otlp]
          # processors: [memory_limiter, batch]
          processors:
          exporters: [debug]
