[project]
name = "friendly-computing-machine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "qmastermoo", email = "cpsaicontact@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
friendly-computing-machine = "friendly_computing_machine:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
