[project]
name = "friendly-computing-machine"
version = "0.1.0"
description = "slackbot"
readme = "README.md"
authors = [
    { name = "qmastermoo", email = "alex.harding@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
fcm = "friendly_computing_machine:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
