"""empty message

Revision ID: 781825fccd3f
Revises: ee99d554acba
Create Date: 2024-11-30 14:26:39.929944

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "781825fccd3f"
down_revision: Union[str, None] = "ee99d554acba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_fcm_slackmessage_slack_channel_id"),
        "slackmessage",
        ["slack_channel_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackmessage_slack_parent_user_id"),
        "slackmessage",
        ["slack_parent_user_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackmessage_slack_team_id"),
        "slackmessage",
        ["slack_team_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackmessage_slack_user_id"),
        "slackmessage",
        ["slack_user_id"],
        unique=False,
        schema="fcm",
    )
    op.add_column(
        "slackuser",
        sa.Column(
            "slack_team_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        schema="fcm",
    )
    op.add_column(
        "slackuser",
        sa.Column("slack_team_id", sa.Integer(), nullable=True),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackuser_slack_team_id"),
        "slackuser",
        ["slack_team_id"],
        unique=False,
        schema="fcm",
    )
    op.create_foreign_key(
        None,
        "slackuser",
        "slackteam",
        ["slack_team_id"],
        ["id"],
        source_schema="fcm",
        referent_schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slackuser", schema="fcm", type_="foreignkey")
    op.drop_index(
        op.f("ix_fcm_slackuser_slack_team_id"), table_name="slackuser", schema="fcm"
    )
    op.drop_column("slackuser", "slack_team_id", schema="fcm")
    op.drop_column("slackuser", "slack_team_slack_id", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_slackmessage_slack_user_id"),
        table_name="slackmessage",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_slackmessage_slack_team_id"),
        table_name="slackmessage",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_slackmessage_slack_parent_user_id"),
        table_name="slackmessage",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_slackmessage_slack_channel_id"),
        table_name="slackmessage",
        schema="fcm",
    )
    # ### end Alembic commands ###
