"""empty message

Revision ID: 2dd4797c78c2
Revises: 781825fccd3f
Create Date: 2024-11-30 15:28:07.549167

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dd4797c78c2"
down_revision: Union[str, None] = "781825fccd3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_status_as_of",
        "taskinstance",
        ["status", sa.text("as_of DESC")],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_status_as_of", table_name="taskinstance", schema="fcm")
    # ### end Alembic commands ###
