"""empty message

Revision ID: faba61bbecf4
Revises: 92d6ff362a93
Create Date: 2024-11-10 16:47:22.812219

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faba61bbecf4"
down_revision: Union[str, None] = "92d6ff362a93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slackmessage",
        "slack_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
        schema="fcm",
    )
    op.drop_index(
        "ix_fcm_slackmessage_slack_id", table_name="slackmessage", schema="fcm"
    )
    op.create_index(
        op.f("ix_fcm_slackmessage_slack_id"),
        "slackmessage",
        ["slack_id"],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_slackmessage_slack_id"), table_name="slackmessage", schema="fcm"
    )
    op.create_index(
        "ix_fcm_slackmessage_slack_id",
        "slackmessage",
        ["slack_id"],
        unique=True,
        schema="fcm",
    )
    op.alter_column(
        "slackmessage",
        "slack_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
        schema="fcm",
    )
    # ### end Alembic commands ###
