"""poll tables

Revision ID: abc123456789
Revises: 71e2c8de4b19
Create Date: 2024-12-25 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abc123456789"
down_revision: Union[str, None] = "71e2c8de4b19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poll",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("slack_channel_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slack_user_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slack_message_id", sa.Integer(), nullable=True),
        sa.Column("slack_message_ts", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["slack_message_id"],
            ["fcm.slackmessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_poll_slack_channel_slack_id"),
        "poll",
        ["slack_channel_slack_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_poll_slack_user_slack_id"),
        "poll",
        ["slack_user_slack_id"],
        unique=False,
        schema="fcm",
    )
    op.create_table(
        "polloption",
        sa.Column("poll_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["fcm.poll.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_polloption_poll_id"),
        "polloption",
        ["poll_id"],
        unique=False,
        schema="fcm",
    )
    op.create_table(
        "pollvote",
        sa.Column("poll_id", sa.Integer(), nullable=False),
        sa.Column("poll_option_id", sa.Integer(), nullable=False),
        sa.Column("slack_user_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["fcm.poll.id"],
        ),
        sa.ForeignKeyConstraint(
            ["poll_option_id"],
            ["fcm.polloption.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_pollvote_poll_id"),
        "pollvote",
        ["poll_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_pollvote_poll_option_id"),
        "pollvote",
        ["poll_option_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_pollvote_slack_user_slack_id"),
        "pollvote",
        ["slack_user_slack_id"],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_pollvote_slack_user_slack_id"),
        table_name="pollvote",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_pollvote_poll_option_id"),
        table_name="pollvote",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_pollvote_poll_id"),
        table_name="pollvote",
        schema="fcm",
    )
    op.drop_table("pollvote", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_polloption_poll_id"),
        table_name="polloption",
        schema="fcm",
    )
    op.drop_table("polloption", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_poll_slack_user_slack_id"),
        table_name="poll",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_poll_slack_channel_slack_id"),
        table_name="poll",
        schema="fcm",
    )
    op.drop_table("poll", schema="fcm")
    # ### end Alembic commands ###