"""add workflow_id to poll table

Revision ID: def123456789
Revises: abc123456789
Create Date: 2025-06-13 06:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "def123456789"
down_revision: Union[str, None] = "abc123456789"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poll",
        sa.Column("workflow_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_poll_workflow_id"),
        "poll",
        ["workflow_id"],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_poll_workflow_id"),
        table_name="poll",
        schema="fcm",
    )
    op.drop_column("poll", "workflow_id", schema="fcm")
    # ### end Alembic commands ###