"""musicpoll

Revision ID: c59bf523de2d
Revises: ae220408773c
Create Date: 2025-03-08 17:05:52.094377

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c59bf523de2d"
down_revision: Union[str, None] = "ae220408773c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "musicpoll",
        sa.Column("slack_channel_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["slack_channel_id"],
            ["fcm.slackchannel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_musicpoll_slack_channel_id"),
        "musicpoll",
        ["slack_channel_id"],
        unique=False,
        schema="fcm",
    )
    op.create_table(
        "musicpollinstance",
        sa.Column("music_poll_id", sa.Integer(), nullable=False),
        sa.Column("slack_message_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("next_instance_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["music_poll_id"],
            ["fcm.musicpoll.id"],
        ),
        sa.ForeignKeyConstraint(
            ["next_instance_id"],
            ["fcm.musicpollinstance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_message_id"],
            ["fcm.slackmessage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_musicpollinstance_music_poll_id"),
        "musicpollinstance",
        ["music_poll_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_musicpollinstance_slack_message_id"),
        "musicpollinstance",
        ["slack_message_id"],
        unique=False,
        schema="fcm",
    )
    op.create_table(
        "musicpollresponse",
        sa.Column("music_poll_instance_id", sa.Integer(), nullable=False),
        sa.Column("slack_user_id", sa.Integer(), nullable=False),
        sa.Column("slack_message_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["music_poll_instance_id"],
            ["fcm.musicpollinstance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_message_id"],
            ["fcm.slackmessage.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_user_id"],
            ["fcm.slackuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_musicpollresponse_music_poll_instance_id"),
        "musicpollresponse",
        ["music_poll_instance_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_musicpollresponse_slack_message_id"),
        "musicpollresponse",
        ["slack_message_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_musicpollresponse_slack_user_id"),
        "musicpollresponse",
        ["slack_user_id"],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_musicpollresponse_slack_user_id"),
        table_name="musicpollresponse",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_musicpollresponse_slack_message_id"),
        table_name="musicpollresponse",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_musicpollresponse_music_poll_instance_id"),
        table_name="musicpollresponse",
        schema="fcm",
    )
    op.drop_table("musicpollresponse", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_musicpollinstance_slack_message_id"),
        table_name="musicpollinstance",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_musicpollinstance_music_poll_id"),
        table_name="musicpollinstance",
        schema="fcm",
    )
    op.drop_table("musicpollinstance", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_musicpoll_slack_channel_id"), table_name="musicpoll", schema="fcm"
    )
    op.drop_table("musicpoll", schema="fcm")
    # ### end Alembic commands ###
