"""empty message

Revision ID: 519e557e2a08
Revises: c59bf523de2d
Create Date: 2025-04-15 21:28:54.520588

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "519e557e2a08"
down_revision: Union[str, None] = "c59bf523de2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slackcommand",
        sa.Column(
            "caller_slack_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("command_base", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("command_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "slack_channel_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_channel_id", sa.Integer(), nullable=True),
        sa.Column("slack_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["slack_channel_id"],
            ["fcm.slackchannel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_user_id"],
            ["fcm.slackuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackcommand_caller_slack_user_id"),
        "slackcommand",
        ["caller_slack_user_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackcommand_slack_channel_id"),
        "slackcommand",
        ["slack_channel_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackcommand_slack_user_id"),
        "slackcommand",
        ["slack_user_id"],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_slackcommand_slack_user_id"),
        table_name="slackcommand",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_slackcommand_slack_channel_id"),
        table_name="slackcommand",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_slackcommand_caller_slack_user_id"),
        table_name="slackcommand",
        schema="fcm",
    )
    op.drop_table("slackcommand", schema="fcm")
    # ### end Alembic commands ###
