"""empty message

Revision ID: ae4cffd9893a
Revises: 84c9ddd72f4c
Create Date: 2025-03-08 13:30:36.026108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae4cffd9893a"
down_revision: Union[str, None] = "84c9ddd72f4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "musicpollinstance",
        sa.Column("next_instance", sa.Integer(), nullable=True),
        schema="fcm",
    )
    op.create_foreign_key(
        None,
        "musicpollinstance",
        "musicpollinstance",
        ["next_instance"],
        ["id"],
        source_schema="fcm",
        referent_schema="fcm",
    )
    op.drop_column("musicpollinstance", "closed_at", schema="fcm")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "musicpollinstance",
        sa.Column(
            "closed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        schema="fcm",
    )
    op.drop_constraint(None, "musicpollinstance", schema="fcm", type_="foreignkey")
    op.drop_column("musicpollinstance", "next_instance", schema="fcm")
    # ### end Alembic commands ###
