"""empty message

Revision ID: a4fe22aef5af
Revises: 2dd4797c78c2
Create Date: 2025-02-14 19:03:48.629475

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4fe22aef5af"
down_revision: Union[str, None] = "2dd4797c78c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genaitext",
        sa.Column(
            "slack_channel_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "slack_user_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response_as_of", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_channel_id", sa.Integer(), nullable=True),
        sa.Column("slack_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["slack_channel_id"],
            ["fcm.slackchannel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_user_id"],
            ["fcm.slackuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_genaitext_created_at"),
        "genaitext",
        ["created_at"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_genaitext_response_as_of"),
        "genaitext",
        ["response_as_of"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_genaitext_slack_channel_id"),
        "genaitext",
        ["slack_channel_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_genaitext_slack_channel_slack_id"),
        "genaitext",
        ["slack_channel_slack_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_genaitext_slack_user_id"),
        "genaitext",
        ["slack_user_id"],
        unique=False,
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_genaitext_slack_user_slack_id"),
        "genaitext",
        ["slack_user_slack_id"],
        unique=False,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_genaitext_slack_user_slack_id"),
        table_name="genaitext",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_genaitext_slack_user_id"), table_name="genaitext", schema="fcm"
    )
    op.drop_index(
        op.f("ix_fcm_genaitext_slack_channel_slack_id"),
        table_name="genaitext",
        schema="fcm",
    )
    op.drop_index(
        op.f("ix_fcm_genaitext_slack_channel_id"), table_name="genaitext", schema="fcm"
    )
    op.drop_index(
        op.f("ix_fcm_genaitext_response_as_of"), table_name="genaitext", schema="fcm"
    )
    op.drop_index(
        op.f("ix_fcm_genaitext_created_at"), table_name="genaitext", schema="fcm"
    )
    op.drop_table("genaitext", schema="fcm")
    # ### end Alembic commands ###
