"""empty message

Revision ID: 81e4579915ed
Revises: 519e557e2a08
Create Date: 2025-05-27 23:40:40.201334

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81e4579915ed"
down_revision: Union[str, None] = "519e557e2a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manmanstatusupdate",
        sa.Column("current_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("service_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("manmanstatusupdate", schema="fcm")
    # ### end Alembic commands ###
