"""empty message

Revision ID: 92d6ff362a93
Revises:
Create Date: 2024-11-10 15:22:27.361897

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92d6ff362a93"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("create schema fcm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slackchannel",
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_music_poll", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackchannel_slack_id"),
        "slackchannel",
        ["slack_id"],
        unique=True,
        schema="fcm",
    )
    op.create_table(
        "slackteam",
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackteam_slack_id"),
        "slackteam",
        ["slack_id"],
        unique=True,
        schema="fcm",
    )
    op.create_table(
        "slackuser",
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackuser_slack_id"),
        "slackuser",
        ["slack_id"],
        unique=True,
        schema="fcm",
    )
    op.create_table(
        "slackmessage",
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "slack_team_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "slack_channel_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "slack_user_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("thread_ts", sa.DateTime(), nullable=True),
        sa.Column(
            "parent_user_slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("processed_date", sa.DateTime(), nullable=True),
        sa.Column("slack_team_id", sa.Integer(), nullable=True),
        sa.Column("slack_channel_id", sa.Integer(), nullable=True),
        sa.Column("slack_user_id", sa.Integer(), nullable=True),
        sa.Column("slack_parent_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["slack_channel_id"],
            ["fcm.slackchannel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_parent_user_id"],
            ["fcm.slackuser.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_team_id"],
            ["fcm.slackteam.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slack_user_id"],
            ["fcm.slackuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fcm",
    )
    op.create_index(
        op.f("ix_fcm_slackmessage_slack_id"),
        "slackmessage",
        ["slack_id"],
        unique=True,
        schema="fcm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fcm_slackmessage_slack_id"), table_name="slackmessage", schema="fcm"
    )
    op.drop_table("slackmessage", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_slackuser_slack_id"), table_name="slackuser", schema="fcm"
    )
    op.drop_table("slackuser", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_slackteam_slack_id"), table_name="slackteam", schema="fcm"
    )
    op.drop_table("slackteam", schema="fcm")
    op.drop_index(
        op.f("ix_fcm_slackchannel_slack_id"), table_name="slackchannel", schema="fcm"
    )
    op.drop_table("slackchannel", schema="fcm")
    # ### end Alembic commands ###
    op.execute("drop schema fcm")
