apiVersion: batch/v1
kind: Job
metadata:
  name: fcm-migration-job{{- if .Values.deployment.name }}-{{ .Values.deployment.name }}{{- end }}
  namespace: {{ .Values.namespace }}
  labels:
    app: friendly-computing-machine
    component: migration
  annotations:
    {{- if and .Values.argocd.enabled .Values.argocd.useSyncWaves }}
    # Argo CD sync wave annotations (Helm hooks automatically skipped)
    "argocd.argoproj.io/sync-wave": "{{ .Values.argocd.migrationSyncWave }}"
    "argocd.argoproj.io/hook": "Skip"
    {{- else }}
    # Standard Helm hooks (for local development)
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    {{- if .Values.argocd.enabled }}
    # Argo CD specific annotations
    "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
    "argocd.argoproj.io/sync-options": "Replace=true"
    {{- end }}
spec:
  {{- if .Values.argocd.enabled }}
  # Ensure job completes before Argo considers sync successful
  completions: 1
  parallelism: 1
  {{- end }}
  template:
    metadata:
      labels:
        app: friendly-computing-machine
        component: migration
    spec:
      restartPolicy: Never
      containers:
      - name: fcm-migration
        image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        args:
          - migration
          - --log-otlp
          - run
        env:
          - name: DATABASE_URL
            value: {{ .Values.env.db.url }}
          - name: APP_ENV
            value: {{ .Values.env.app_env }}
          - name: OTEL_SERVICE_NAME
            value: fcm-migration-job
          - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
            value: {{ .Values.env.otelCollector.logs.endpoint }}
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: {{ .Values.env.otelCollector.traces.endpoint }}
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "deployment-name={{ .Values.deployment.name }},component=migration"
  backoffLimit: 3
  activeDeadlineSeconds: 300
