apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcm-temporal-worker-deployment{{- if .Values.deployment.name }}-{{- end }}{{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: fcm-temporal-worker
    app.kubernetes.io/component: slackbot
  {{- if and .Values.argocd.enabled .Values.argocd.useSyncWaves }}
  annotations:
    "argocd.argoproj.io/sync-wave": "0"
  {{- end }}
spec:
  replicas: {{ .Values.temporal.replicas }} # Consider if worker replicas should be configured separately
  selector:
    matchLabels:
      app: fcm-temporal-worker
  template:
    metadata:
      namespace: {{ .Values.namespace }} # Assuming same namespace, adjust if needed
      labels:
        app: fcm-temporal-worker
    spec:
      containers:
      - name: fcm-temporal-worker
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        resources: # Adjust resources based on worker needs
          requests:
            cpu: {{ .Values.temporal.resources.requests.cpu }}
            memory: {{ .Values.temporal.resources.requests.memory }}
          limits:
            cpu: {{ .Values.temporal.resources.limits.cpu }}
            memory: {{ .Values.temporal.resources.limits.memory }}
        ports:
        - containerPort: 7654
          name: health
        {{- if .Values.temporal.health.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        {{- end }}
        args:
          - workflow
          - --log-otlp
          - run
          # migrations run as pre-install job
          - --skip-migration-check
        env:
          - name: APP_ENV
            value: {{ .Values.env.app_env }}
          - name: TEMPORAL_HOST
            value: {{ .Values.env.temporal.host }}
          - name: SLACK_BOT_TOKEN
            value: {{ .Values.env.slack.botToken }}
          - name: SLACK_APP_TOKEN
            value: {{ .Values.env.slack.appToken }}
          - name: GOOGLE_API_KEY
            value: {{ .Values.env.google.api_key }}
          - name: DATABASE_URL
            value: {{ .Values.env.db.url }}
          - name: OTEL_SERVICE_NAME
            value: fcm-temporal-worker
          - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
            value: {{ .Values.env.otelCollector.logs.endpoint }}
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: {{ .Values.env.otelCollector.traces.endpoint }}
  {{/*          - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT*/}}
  {{/*            value: {{ .Values.env.otelCollector.metrics.endpoint }}*/}}
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "deployment-name=temporal-worker{{- if .Values.deployment.name }}-{{ .Values.deployment.name }}{{- end }}" # Adjusted attribute
