image:
  name: "ghcr.io/whale-net/friendly-computing-machine"
  tag: ""

namespace: fcm

deployment:
  name: ""
  skip_migration_check: true
  replicas: 1

env:
  db:
    url: <postgresql+psycopg2://user:password@host:port/database>
  slack:
    botToken: <slack_bot_token>
    appToken: <slack_app_token>
  otelCollector:
    logs:
      endpoint: <logs_endpoint>
    traces:
      endpoint: <traces_endpoint>
#    metrics:
#      endpoint: <metrics_endpoint>
